[Project]
name = "dpt-media-control"

[[InputPins]]

id="I#17"
dispaly_name = "input1"
type = "input"
gpio_pin = 17
activation_delay = 0
triggered_pins = ["O#23"]

[[InputPins]]

id="I#27"
display_name = "input2"
type = "input"
gpio_pin = 27
activation_delay = 0
triggered_pins = ["O#24"]

[[InputPins]]

id="I#22"
display_name = "input3"
type = "input"
gpio_pin = 22
activation_delay = 0

triggered_pins = ["O#25", "V#1"]

[[OutputPins]]

id="O#23"
display_name = "output1"
type = "output"
gpio_pin = 23
hold_time = 10
trigger_method = "hold"

[[OutputPins]]

id="O#24"
display_name = "output2"
type = "output"
gpio_pin = 24
hold_time = 10
trigger_method = "hold"
pins_to_block= []

[[OutputPins]]

id="O#25"
display_name = "output3"
type = "output"
gpio_pin = 25
hold_time = 0
trigger_method = "while_input"
pins_to_block= []

[[VirtualPins]]
id="V#1"
display_name = "v1"
gpio_pin = -1
type = "virtual"
ip_address = "200.100.0.100"
virtual_trigger_method = "pjlink_power_on" # "pjlink_power_on", "pjlink_power_off", "nothing"
